[package]
name = "bwmpq"
version = "0.1.0"
edition = "2021"

[dependencies]
stormlib-bindings = { git = "ssh://git@github.com/zzlk/stormlib-bindings.git" }

serde = { version = "*", features = ["derive"] }
encoding_rs = "*"
anyhow = { version = "*", features = ["backtrace"] }
uuid = { version = "*", features = ["v4"], optional = true }

scopeguard = "*"
lazy_static = "*"
phf = { version = "0.10", features = ["macros"] }

tracing = "*"

serde-big-array = "*"


[dev-dependencies]
reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1", features = ["full"] }
walkdir = { version = "*" }
rayon = { version = "*" }
futures = { version = "*" }
rand = { version = "*" }
tempfile = { version = "*" }
sha2 = "*"
